# Generated by Django 3.2.5 on 2022-12-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_intership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intership',
            new_name='Internship',
        ),
    ]
