# Generated by Django 3.2.5 on 2022-12-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_intership_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='catego',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
